server.port=9090

Json_Files_Path=APIdocs/Json_Data/


s3_bucket_pdf_files_location=/var/tmp/GenBookmarks/externalId/SourceFiles/
Merged_Document_Path=/var/tmp/GenBookmarks/externalId/Bookmark/
Extract_FormNames_Path=/var/tmp/GenBookmarks/externalId/ExtractFormNames/
Gen_CsvFile_Path=/var/tmp/GenBookmarks/externalId/CSVFiles/


spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB